/* Auto-generated by genmsg_cpp for file /home/john/fuerte_workspace/jb_blob_tracker/msg/blob.msg */
#ifndef JB_BLOB_TRACKER_MESSAGE_BLOB_H
#define JB_BLOB_TRACKER_MESSAGE_BLOB_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace jb_blob_tracker
{
template <class ContainerAllocator>
struct blob_ {
  typedef blob_<ContainerAllocator> Type;

  blob_()
  : x(0.0)
  , y(0.0)
  , variance(0.0)
  , size(0.0)
  , ID(0)
  , header()
  {
  }

  blob_(const ContainerAllocator& _alloc)
  : x(0.0)
  , y(0.0)
  , variance(0.0)
  , size(0.0)
  , ID(0)
  , header(_alloc)
  {
  }

  typedef float _x_type;
  float x;

  typedef float _y_type;
  float y;

  typedef float _variance_type;
  float variance;

  typedef float _size_type;
  float size;

  typedef int32_t _ID_type;
  int32_t ID;

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;


  typedef boost::shared_ptr< ::jb_blob_tracker::blob_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::jb_blob_tracker::blob_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct blob
typedef  ::jb_blob_tracker::blob_<std::allocator<void> > blob;

typedef boost::shared_ptr< ::jb_blob_tracker::blob> blobPtr;
typedef boost::shared_ptr< ::jb_blob_tracker::blob const> blobConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::jb_blob_tracker::blob_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::jb_blob_tracker::blob_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace jb_blob_tracker

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::jb_blob_tracker::blob_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::jb_blob_tracker::blob_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::jb_blob_tracker::blob_<ContainerAllocator> > {
  static const char* value() 
  {
    return "3308346faa57a9799f8d7a45b76eeede";
  }

  static const char* value(const  ::jb_blob_tracker::blob_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x3308346faa57a979ULL;
  static const uint64_t static_value2 = 0x9f8d7a45b76eeedeULL;
};

template<class ContainerAllocator>
struct DataType< ::jb_blob_tracker::blob_<ContainerAllocator> > {
  static const char* value() 
  {
    return "jb_blob_tracker/blob";
  }

  static const char* value(const  ::jb_blob_tracker::blob_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::jb_blob_tracker::blob_<ContainerAllocator> > {
  static const char* value() 
  {
    return "float32 x\n\
float32 y\n\
float32 variance\n\
float32 size\n\
int32 ID\n\
Header header\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::jb_blob_tracker::blob_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::jb_blob_tracker::blob_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.variance);
    stream.next(m.size);
    stream.next(m.ID);
    stream.next(m.header);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct blob_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::jb_blob_tracker::blob_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::jb_blob_tracker::blob_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "variance: ";
    Printer<float>::stream(s, indent + "  ", v.variance);
    s << indent << "size: ";
    Printer<float>::stream(s, indent + "  ", v.size);
    s << indent << "ID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.ID);
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
  }
};


} // namespace message_operations
} // namespace ros

#endif // JB_BLOB_TRACKER_MESSAGE_BLOB_H

